server:
  port: 9000
spring:
  application:
    name: "cards"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
    show-sql: true
  sql:
    init:
      mode: always

build:
  version: "1.0"

cards:
  message: "welcome "
  contactDetail:
    name: "John"
    email: "john@gmail.com"
  onCallSupport:
    - (080) 123456
    - (080) 987654
    -
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "cards"
    description: "cards service"
    version: "1.0.0"


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      service:
        cards: DEBUG

