services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-compose.yml
      service: network-deploy-service

  configserver:
    image: "ponaliprakash/config-service:s7"
    container_name: configserver_ms
    ports:
      - "8072:8072"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent configserver:8072/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-compose.yml
      service: microservice-base-config

  accounts:
    image: "ponaliprakash/account-service:s6"
    container_name: account_ms
    ports:
      - "8080:8080"
    extends:
      file: common-compose.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "accounts"

  cards:
    image: "ponaliprakash/card-service:s6"
    container_name: cards_ms
    ports:
      - "9000:9000"
    extends:
      file: common-compose.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "cards"

  loans:
    image: "ponaliprakash/loan-service:s6"
    container_name: loans_ms
    ports:
      - "8090:8090"
    extends:
      file: common-compose.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "loans"

networks:
  banksnetwork:
    driver: bridge



