services:
  configserver:
    image: "ponaliprakash/account-service:v1"
    container_name: account_ms
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banksnetwork

  accounts:
    image: "ponaliprakash/account-service:v1"
    container_name: account_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banksnetwork
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://localhost:8071/"
      SPRING_PROFILES_ACTIVE: default
  cards:
    image: "ponaliprakash/card-service:v1"
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banksnetwork
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://localhost:8071/"
      SPRING_PROFILES_ACTIVE: default
  loans:
    image: "ponaliprakash/loan-service:v1"
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banksnetwork
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://localhost:8071/"
      SPRING_PROFILES_ACTIVE: default
networks:
  banksnetwork:
    driver: bridge



