server:
  port: 8071

spring:
  application:
    name: configserrver
  profiles:
    # active: native # class path
      active: git
  cloud:
    config:
      server:
        git:
          clone-on-start: true
      # native:
          # search-locations: "file:///Users//prakashponali//practice//Document//config"
          # search-locations: "classpath:/config"
          uri: https://github.com/pponali/config-server-configurations.git
          timeout: 5
          force-pull: true
          default-label: main
encrypt:
  key: "324523459SJDHFIJKLSDHFGJH28734587230498578"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true