server:
  port: 8080
spring:
  rabbitmq:
    port: 5672
    host: "localhost"
    username: "guest"
    password: "guest"
  application:
    name: accounts
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8072/"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
    show-sql: true
  sql:
    init:
      mode: always

build:
  version: "1.0"

accounts:
  message: "welcome "
  contactDetail:
    name: "John"
    email: "john@gmail.com"
  onCallSupport:
    - (080) 123456
    - (080) 987654
    -
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

