server:
  port: 9000

build:
  version: "1.0"

cards:
  message: "welcome Default"
  contactDetail:
    name: "Default"
    email: "default@gmail.com"
  onCallSupport:
    - (080) 000000
    - (080) 111111
spring:
  profiles:
    active: "prod"
  application:
    name: cards
  config:
    import: "optional:configserver:http://localhost:8072/"
  rabbitmq:
    port: 5672
    host: "localhost"
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true